name: Checkout and List Files

on:
  push:
    branches:
      - main # This workflow runs on pushes to the main branch
  workflow_dispatch:

jobs:
  build: # Define a job named 'build'
    runs-on: ubuntu-latest # Specify the runner environment (e.g., Ubuntu Linux)

    steps: # Define the steps for this job
      - name: Checkout repository # A descriptive name for the step
        uses: actions/checkout@v3 # Use the checkout action

      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.TEST_REPO }}
          token: ${{ secrets.AUTH_TOKEN }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: List files in the workspace # Another descriptive name
        run: | # Run a multi-line script
          echo "Listing files in the GITHUB_WORKSPACE:"
          pwd # Print the current working directory (should be GITHUB_WORKSPACE)
          ls -al # List all files and directories in the current location

      - name: Show test folder
        run: |
          ls tests -al
